### ISSUE TITLE
Front.Sciter is undefined

### ISSUE THREAD

**Issue by SparK-Cruz** [brokenbydefault/Nanollet#1]
https://github.com/BrokenByDefault/Nanollet/blob/350c21b128fba3b52ea5cff9883c12d3251548d8/GUI/window.go#L47

Right after go getting it:
```
# github.com/brokenbydefault/Nanollet/GUI
go/src/github.com/brokenbydefault/Nanollet/GUI/window.go:47:55: undefined: Front.Sciter
```

Any quick fix or solution to read Front info and pass that to sciter.link file?

Edit:
I think it might have something to do with https://github.com/BrokenByDefault/Nanollet/commit/350c21b128fba3b52ea5cff9883c12d3251548d8

Any way I can generate those files in my local copy?

Edit2:
I was reading their readme and aparently I have to install scite-sdk first, and then try to build anything...
Do you have building steps somewhere? To put on the readme file...

**Comment by Inkeliz** [comment]
Theres files are created by the generator, at [gen.go](https://github.com/BrokenByDefault/Nanollet/blob/master/GUI/Generator/gen.go).

1. Run `go -x github.com/BrokenByDefault/Nanollet`, that will clone all files.
2. Download the Sciter SDK from https://sciter.com/download/.
3. Copy the `sciter.dll`, `libsciter-gtk-64.so` and `sciter-osx-64.dylib` from `sciter-sdk.zip` to the folder (here the `main.go` are). 

It can be little confusing. If you are on Windows, open the `sciter-sdk.zip`, and copy the `/bin/64/sciter.dll` to `%GOPATH%\src\github.com\brokenbydefault\Nanollet`. Repeat the same process to `/bin.osx/sciter-osx-64.dylib` and  `bin.gtk/x64/libsciter-gtk-64.so`. 

The names of the files can change, it that is the case, just rename accordingly. In the end will be something like:

> ...
> | - .gitattributes
> | - .gitignore
> | - **libsciter-gtk-64.so**
> | - LICENSE
> | - main.go
> | - Nanollet.exe.manifest
> | - README.md
> | - README-Image1.png
> | - **sciter.dll**
> | - **sciter-osx-64.dylib**

4. Run `go generate`.

Now, you can `go build`. 

If not, I think you need to setup the GCC for CGO, in this case you need to download [mingw64-gcc](https://sourceforge.net/projects/mingw-w64/), or another compiler, and set the envioment variable. If you are on Windows, go to `Control Panel` > `System` > `Advanced Settings` (on left sidebar) > `Envioment Variables`, then select `PATH` and click on `Edit`. You should add the _mingw-64_, which by default is living on `C:/mingw64/bin`.

**Comment by SparK-Cruz** [comment]
I use Arch, will attempt to build it again when I get home.

**Comment by lane-c-wagner** [comment]
I think those dependencies should be included in the repo for safe keeping and first-time builds.
