### ISSUE TITLE
No open block created.

### ISSUE THREAD

**Issue by lane-c-wagner** [brokenbydefault/Nanollet#16]
Not sure what I'm doing wrong.... I created an account and then sent .0001 nano to it to make sure it works. No money was received so I checked using the nanode tool. Address never had an opening block....

https://www.nanode.co/account/nano_39mfay8c7b93dsqy564z4qg8cfh1db6dskjfdygzth353t7y39tm7ia7xd3k

**Comment by lane-c-wagner** [comment]
I was using canoe, I wonder if canoe won't send if there is no open block? I tried using .001

**Comment by Inkeliz** [comment]
I did not use canoe. However, the 'open block' can only be released once it has received something.   You can (or should) be able to send to any address, including those that are not open. 

For now, I think it's not a problem with Nanollet.

**Comment by lane-c-wagner** [comment]
I got your transaction. Must be a canoe issue. We can close this.
