### ISSUE TITLE
MacOS version 

### ISSUE THREAD

**Issue by pedfx** [brokenbydefault/Nanollet#8]

**Comment by slowaways** [comment]
+1

**Comment by Inkeliz** [comment]
Is weird. You are trying to use it as a `.app` or as executable (generated by `go build`)?

**Comment by pedfx** [comment]
As executable
<img width="397" alt="captura de tela 2018-09-30 as 12 59 58" src="https://user-images.githubusercontent.com/12234380/46259529-07910480-c4b1-11e8-9193-7ad4ce9f65d8.png">

**Comment by dandanua** [comment]
I have same issue

**Comment by pedfx** [comment]
#32 @Inkeliz made it

**Comment by Inkeliz** [comment]
The [last release](https://github.com/brokenbydefault/Nanollet/releases) supports MacOS/Darwin. 👍
